version: '3.8'

services:
  # OpenStack (simplified for demonstration)
  openstack:
    image: kolla/ubuntu-source-keystone:latest
    container_name: openstack
    ports:
      - "5000:5000"
      - "35357:35357"
    environment:
      - KEYSTONE_ADMIN_PASSWORD=admin
    networks:
      - my_network

  # FTP Server
  ftp:
    image: stilliard/pure-ftpd:latest
    container_name: ftp_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - FTP_USER_NAME=user
      - FTP_USER_PASS=password
      - FTP_USER_HOME=/home/user
    volumes:
      - ./ftp_data:/home/user
    networks:
      - my_network

  # Email Service (Postfix)
  email:
    image: catatnight/postfix:latest
    container_name: email_server
    environment:
      - maildomain=example.com
      - smtp_user=user:password
    ports:
      - "25:25"
    networks:
      - my_network

  # ERP Software (Odoo)
  erp:
    image: odoo:latest
    container_name: erp_server
    ports:
      - "8069:8069"
    depends_on:
      - postgresql
    environment:
      - HOST=postgresql
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - my_network

  # Kafka with Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - my_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - my_network

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - my_network

  # PostgreSQL
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  # CRM (SuiteCRM)
  crm:
    image: suitecrm/suitecrm:latest
    container_name: crm
    ports:
      - "8080:80"
    depends_on:
      - postgresql
    environment:
      - DB_HOST=postgresql
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoo
    networks:
      - my_network

  # Marketing Service (Mautic)
  marketing:
    image: mautic/mautic:latest
    container_name: marketing
    ports:
      - "8081:80"
    depends_on:
      - postgresql
    environment:
      - MAUTIC_DB_HOST=postgresql
      - MAUTIC_DB_USER=odoo
      - MAUTIC_DB_PASSWORD=odoo
      - MAUTIC_DB_NAME=odoo
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
